"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class StreamAnalyzeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class MediaFrame(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        PTS_FIELD_NUMBER: _builtins.int
        DTS_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        DATA_FIELD_NUMBER: _builtins.int
        pts: _builtins.int
        """フレーム画像の表示時刻
        1970-01-01 00:00:00 UTC からの経過時間, 1/90,000秒単位
        """
        dts: _builtins.int
        """フレーム画像のデコード時刻
        1970-01-01 00:00:00 UTC からの経過時間, 1/90,000秒単位
        """
        type: _builtins.int
        """パケット種別、ビットフィールド

        | byte | bit |
        |------|-----|-------
        |  3~1 |     | 未使用
        |    0 |   7 | 0: 非キーフレーム, 1: キーフレーム
        |    0 | 6~0 | 0: H264パケット, 1: AACパケット

        上位バイト 3 - 0 下位バイト
        MSB 7 - 0 LSB
        """
        data: _builtins.bytes
        """H264パケットまたはAACパケット"""
        def __init__(
            self,
            *,
            pts: _builtins.int = ...,
            dts: _builtins.int = ...,
            type: _builtins.int = ...,
            data: _builtins.bytes = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "dts", b"dts", "pts", b"pts", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    MEDIA_FRAME_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def media_frame(self) -> Global___StreamAnalyzeRequest.MediaFrame: ...
    def __init__(
        self,
        *,
        media_frame: Global___StreamAnalyzeRequest.MediaFrame | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["media_frame", b"media_frame"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["media_frame", b"media_frame"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamAnalyzeRequest: _TypeAlias = StreamAnalyzeRequest  # noqa: Y015

@_typing.final
class StreamAnalyzeResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class RecordMetrics(_message.Message):
        """時刻と値の組で表現される時系列データを保存できます。

        各時系列データには16文字以内の文字列で表されるラベル（label）を付与でき、
        このラベルによって区別された複数種類の時系列データを保存することができます。
        時系列データは、保存時に5分毎、1時間毎、1日毎にダウンサンプリングされるため、
        保存された時系列データから特定の時刻のデータのみを取得することはできません。
        時系列データは、保存時に時間方向に集計処理が適用され、サポートしている統計値は、
        値の個数 (count)、総和 (sum)、平均値 (avg)、最小値 (min), 最大値 (max) 、null値を0と扱う平均値（avg0）。
        平均値は総和/個数で計算されます。
        """

        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class MetricsEntry(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            KEY_FIELD_NUMBER: _builtins.int
            VALUE_FIELD_NUMBER: _builtins.int
            key: _builtins.str
            value: _builtins.float
            def __init__(
                self,
                *,
                key: _builtins.str = ...,
                value: _builtins.float = ...,
            ) -> None: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        TIMESTAMP_FIELD_NUMBER: _builtins.int
        UNITS_FIELD_NUMBER: _builtins.int
        METRICS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def timestamp(self) -> _timestamp_pb2.Timestamp:
            """このデータが取得された時刻です"""

        @_builtins.property
        def units(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
            """出力した数値データを集計する時間幅を指定します
            "5minutes", "hourly", "daily" の中から一つ以上指定できます。
            """

        @_builtins.property
        def metrics(self) -> _containers.ScalarMap[_builtins.str, _builtins.float]:
            """時系列上の値で、ラベル (16文字以内の文字列) => 4バイト浮動小数点数 のマップです。
            要素数の上限が、契約プランによって設けられる場合があります。
            """

        def __init__(
            self,
            *,
            timestamp: _timestamp_pb2.Timestamp | None = ...,
            units: _abc.Iterable[_builtins.str] | None = ...,
            metrics: _abc.Mapping[_builtins.str, _builtins.float] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["timestamp", b"timestamp"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["metrics", b"metrics", "timestamp", b"timestamp", "units", b"units"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class RecordEvent(_message.Message):
        """特定の条件を満たした時刻における画像認識（構造および意味の抽出）の結果得られた、ユーザーにとって意味のある情報を表します。
        例）エリア入退場、滞留時間超過、速度超過、固定インターバル、構造生成・消滅時

        出力されたイベントは、時刻および付加情報を条件に指定して検索することができます。
        type の情報は前方一致検索が可能であり、また、特定の type を持つイベントが登録された際に、
        事前にデバイスオーナーによって定義された通知手段を用いて、デバイスのオーナーに通知を行うこともできます。
        labels には、そのイベントを機械的に区別するための文字列（ラベル）を複数付与できる。特定のラベルを持つイベントのみを検索することが可能です。
        一つのイベントには、事前に設定された複数種類のジオメトリの設定（ geometry_config_ids）を関連付けることができ、ジオメトリ設定を指定した検索も可能です。
        検索の必要がないが、イベントに付属させたい情報は、 data にJSON形式で持たせることができます。
        また、一つのイベントには、最大一枚の画像を添付できます。
        """

        DESCRIPTOR: _descriptor.Descriptor

        TIMESTAMP_FIELD_NUMBER: _builtins.int
        EVENT_INDEX_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        LABELS_FIELD_NUMBER: _builtins.int
        SCORE_FIELD_NUMBER: _builtins.int
        DATA_FIELD_NUMBER: _builtins.int
        GEOMETRY_CONFIG_IDS_FIELD_NUMBER: _builtins.int
        PICTURE_FIELD_NUMBER: _builtins.int
        event_index: _builtins.str
        """イベントを一意に特定するために analyzerで生成される 36文字以内の文字列です。
        出力するすべてのイベントにおいてユニークである必要があります。
        event_indexが過去のイベントと重複した場合、重複イベントとして扱われるため保存されません。
        """
        type: _builtins.str
        """イベントの種別を表す文字列で、正規表現 `[a-zA-Z0-9_\\-]+(\\.[a-zA-Z0-9_\\-]+)*` にマッチし、
        32文字以内である必要があります。例 `enter.truck`
        """
        score: _builtins.float
        """イベントに付与する数値データです。有効数字6桁までで、6桁より先は四捨五入されます。"""
        @_builtins.property
        def timestamp(self) -> _timestamp_pb2.Timestamp:
            """timestamp はEventの発生した日時です"""

        @_builtins.property
        def labels(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
            """イベントに関連付けられるラベルのリストです。
            各ラベルは、1文字以上16文字以内で、最大10個まで指定できます。
            """

        @_builtins.property
        def data(self) -> _struct_pb2.Struct:
            """任意のJSON Objectと互換のオブジェクトです。
            サイズ上限はJSONシリアライズした際に1kiBです。
            """

        @_builtins.property
        def geometry_config_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
            """イベントに関連するジオメトリ設定IDのリストです。"""

        @_builtins.property
        def picture(self) -> Global___EventPicture:
            """イベントに関連付けられる画像です。"""

        def __init__(
            self,
            *,
            timestamp: _timestamp_pb2.Timestamp | None = ...,
            event_index: _builtins.str = ...,
            type: _builtins.str = ...,
            labels: _abc.Iterable[_builtins.str] | None = ...,
            score: _builtins.float | None = ...,
            data: _struct_pb2.Struct | None = ...,
            geometry_config_ids: _abc.Iterable[_builtins.int] | None = ...,
            picture: Global___EventPicture | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_data", b"_data", "_picture", b"_picture", "_score", b"_score", "data", b"data", "picture", b"picture", "score", b"score", "timestamp", b"timestamp"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_data", b"_data", "_picture", b"_picture", "_score", b"_score", "data", b"data", "event_index", b"event_index", "geometry_config_ids", b"geometry_config_ids", "labels", b"labels", "picture", b"picture", "score", b"score", "timestamp", b"timestamp", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__data: _TypeAlias = _typing.Literal["data"]  # noqa: Y015
        _WhichOneofArgType__data: _TypeAlias = _typing.Literal["_data", b"_data"]  # noqa: Y015
        _WhichOneofReturnType__picture: _TypeAlias = _typing.Literal["picture"]  # noqa: Y015
        _WhichOneofArgType__picture: _TypeAlias = _typing.Literal["_picture", b"_picture"]  # noqa: Y015
        _WhichOneofReturnType__score: _TypeAlias = _typing.Literal["score"]  # noqa: Y015
        _WhichOneofArgType__score: _TypeAlias = _typing.Literal["_score", b"_score"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__data) -> _WhichOneofReturnType__data | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__picture) -> _WhichOneofReturnType__picture | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__score) -> _WhichOneofReturnType__score | None: ...

    @_typing.final
    class RecordObject(_message.Message):
        """最終的にトラッキングしていたオブジェクトがフレームアウトするなどして、トラッキングが終了した場合にはend_timestampを指定してオブジェクト情報を出力すると、
        そのオブジェクトは確定情報と扱われ、以降更新が発生することはできなくなります。

        一つのオブジェクト情報には、data のカラムに収まりきらない追加情報（extra_data）を付与できます。
        例えば、そのオブジェクトをトラッキング中の時間帯における各動画フレームの情報などを想定しています。
        """

        DESCRIPTOR: _descriptor.Descriptor

        START_TIMESTAMP_FIELD_NUMBER: _builtins.int
        END_TIMESTAMP_FIELD_NUMBER: _builtins.int
        OBJECT_INDEX_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        DURATION_FIELD_NUMBER: _builtins.int
        LABELS_FIELD_NUMBER: _builtins.int
        SCORE_FIELD_NUMBER: _builtins.int
        DATA_FIELD_NUMBER: _builtins.int
        GEOMETRY_CONFIG_IDS_FIELD_NUMBER: _builtins.int
        PICTURE_FIELD_NUMBER: _builtins.int
        EXTRA_DATA_FIELD_NUMBER: _builtins.int
        object_index: _builtins.str
        """Objectを一意に特定するために analyzerで生成される 36文字以内の文字列です。
        同じobject_indexを指定して出力するとすでに送信済みのオブジェクト情報を上書きできます。
        """
        type: _builtins.str
        """type はオブジェクト種別を表す文字列で、正規表現 `[a-zA-Z0-9_\\-]+(\\.[a-zA-Z0-9_\\-]+)*` にマッチし、
        32文字以内である必要があります。例 `person.face`
        """
        duration: _builtins.int
        """オブジェクトを検出していた時間です。単位はミリ秒です。"""
        score: _builtins.float
        """オブジェクトに付与する数値データです。有効数字6桁までで、6桁より先は四捨五入されます。"""
        @_builtins.property
        def start_timestamp(self) -> _timestamp_pb2.Timestamp:
            """Objectの検出開始時刻です"""

        @_builtins.property
        def end_timestamp(self) -> _timestamp_pb2.Timestamp:
            """Objectの検出終了時刻です。終了時刻が設定されたオブジェクトはそれ以上更新することができません。"""

        @_builtins.property
        def labels(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
            """オブジェクトに関連付けられるラベルのリストです。
            各ラベルは、1文字以上16文字以内で、最大10個まで指定できます。
            """

        @_builtins.property
        def data(self) -> _struct_pb2.Struct:
            """任意のJSON Objectと互換のオブジェクトです。
            サイズ上限はJSONシリアライズした際に1kiBです。
            """

        @_builtins.property
        def geometry_config_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
            """オブジェクトに関連するジオメトリ設定IDのリストです。"""

        @_builtins.property
        def picture(self) -> _containers.RepeatedCompositeFieldContainer[Global___ObjectPicture]:
            """オブジェクトに関連付けられる画像です。
            画像は最大5枚まで指定できます。
            """

        @_builtins.property
        def extra_data(self) -> Global___ObjectExtraData:
            """オブジェクトに関連付けられる追加のデータです。"""

        def __init__(
            self,
            *,
            start_timestamp: _timestamp_pb2.Timestamp | None = ...,
            end_timestamp: _timestamp_pb2.Timestamp | None = ...,
            object_index: _builtins.str = ...,
            type: _builtins.str = ...,
            duration: _builtins.int | None = ...,
            labels: _abc.Iterable[_builtins.str] | None = ...,
            score: _builtins.float | None = ...,
            data: _struct_pb2.Struct | None = ...,
            geometry_config_ids: _abc.Iterable[_builtins.int] | None = ...,
            picture: _abc.Iterable[Global___ObjectPicture] | None = ...,
            extra_data: Global___ObjectExtraData | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_data", b"_data", "_duration", b"_duration", "_extra_data", b"_extra_data", "_score", b"_score", "data", b"data", "duration", b"duration", "end_timestamp", b"end_timestamp", "extra_data", b"extra_data", "score", b"score", "start_timestamp", b"start_timestamp"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_data", b"_data", "_duration", b"_duration", "_extra_data", b"_extra_data", "_score", b"_score", "data", b"data", "duration", b"duration", "end_timestamp", b"end_timestamp", "extra_data", b"extra_data", "geometry_config_ids", b"geometry_config_ids", "labels", b"labels", "object_index", b"object_index", "picture", b"picture", "score", b"score", "start_timestamp", b"start_timestamp", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__data: _TypeAlias = _typing.Literal["data"]  # noqa: Y015
        _WhichOneofArgType__data: _TypeAlias = _typing.Literal["_data", b"_data"]  # noqa: Y015
        _WhichOneofReturnType__duration: _TypeAlias = _typing.Literal["duration"]  # noqa: Y015
        _WhichOneofArgType__duration: _TypeAlias = _typing.Literal["_duration", b"_duration"]  # noqa: Y015
        _WhichOneofReturnType__extra_data: _TypeAlias = _typing.Literal["extra_data"]  # noqa: Y015
        _WhichOneofArgType__extra_data: _TypeAlias = _typing.Literal["_extra_data", b"_extra_data"]  # noqa: Y015
        _WhichOneofReturnType__score: _TypeAlias = _typing.Literal["score"]  # noqa: Y015
        _WhichOneofArgType__score: _TypeAlias = _typing.Literal["_score", b"_score"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__data) -> _WhichOneofReturnType__data | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__duration) -> _WhichOneofReturnType__duration | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__extra_data) -> _WhichOneofReturnType__extra_data | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__score) -> _WhichOneofReturnType__score | None: ...

    @_typing.final
    class RecordDeviceStatus(_message.Message):
        """デバイスの現在の状態を表す情報です。（例えば、現在の店舗の混雑状況、現在特定のオブジェクトが写っているか否か、など）
        この情報を参照することで、常に最新のデバイスの状態を取得できます。
        最新の更新時刻は記録するが、過去の状態は取得できません。

        ラベル（label）に任意の文字列を指定でき、このラベルによって区別された複数種類の状態を定義できます。
        同一labelでデータを出力すると新しい値でそのステータス情報は更新されます。
        一つのデバイスには10種類までの状態を保存でき、それ以上の状態を保存しようとすると更新時刻が最も古いレコードが削除され、
        新しい状態が登録されます。
        """

        DESCRIPTOR: _descriptor.Descriptor

        TIMESTAMP_FIELD_NUMBER: _builtins.int
        DEVICE_STATUS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def timestamp(self) -> _timestamp_pb2.Timestamp:
            """ステータスの更新時刻です"""

        @_builtins.property
        def device_status(self) -> _containers.RepeatedCompositeFieldContainer[Global___DeviceStatus]:
            """デバイスのステータス情報です。最大10個まで指定できます。"""

        def __init__(
            self,
            *,
            timestamp: _timestamp_pb2.Timestamp | None = ...,
            device_status: _abc.Iterable[Global___DeviceStatus] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["timestamp", b"timestamp"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["device_status", b"device_status", "timestamp", b"timestamp"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class UpdateContext(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        CONTEXT_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def context(self) -> _struct_pb2.Struct:
            """context は同一デバイス/契約の解析処理の間で引き継がれる値です。
            値が未設定の場合、値は更新されません。
            値が存在する場合、次回以降のAnalyzerの呼び出しでその値が渡されます。
            サイズ上限はJSONシリアライズした際に16kiBです。
            空のStructを指定することで既存のContextを削除できます。
            """

        def __init__(
            self,
            *,
            context: _struct_pb2.Struct | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["context", b"context"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["context", b"context"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    RECORD_METRICS_FIELD_NUMBER: _builtins.int
    RECORD_EVENT_FIELD_NUMBER: _builtins.int
    RECORD_OBJECT_FIELD_NUMBER: _builtins.int
    RECORD_DEVICE_STATUS_FIELD_NUMBER: _builtins.int
    UPDATE_CONTEXT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def record_metrics(self) -> Global___StreamAnalyzeResponse.RecordMetrics: ...
    @_builtins.property
    def record_event(self) -> Global___StreamAnalyzeResponse.RecordEvent: ...
    @_builtins.property
    def record_object(self) -> Global___StreamAnalyzeResponse.RecordObject: ...
    @_builtins.property
    def record_device_status(self) -> Global___StreamAnalyzeResponse.RecordDeviceStatus: ...
    @_builtins.property
    def update_context(self) -> Global___StreamAnalyzeResponse.UpdateContext: ...
    def __init__(
        self,
        *,
        record_metrics: Global___StreamAnalyzeResponse.RecordMetrics | None = ...,
        record_event: Global___StreamAnalyzeResponse.RecordEvent | None = ...,
        record_object: Global___StreamAnalyzeResponse.RecordObject | None = ...,
        record_device_status: Global___StreamAnalyzeResponse.RecordDeviceStatus | None = ...,
        update_context: Global___StreamAnalyzeResponse.UpdateContext | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["payload", b"payload", "record_device_status", b"record_device_status", "record_event", b"record_event", "record_metrics", b"record_metrics", "record_object", b"record_object", "update_context", b"update_context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["payload", b"payload", "record_device_status", b"record_device_status", "record_event", b"record_event", "record_metrics", b"record_metrics", "record_object", b"record_object", "update_context", b"update_context"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["record_metrics", "record_event", "record_object", "record_device_status", "update_context"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___StreamAnalyzeResponse: _TypeAlias = StreamAnalyzeResponse  # noqa: Y015

@_typing.final
class EventPicture(_message.Message):
    """EventPictureは、イベントに付与される画像情報を表します"""

    DESCRIPTOR: _descriptor.Descriptor

    CONTENT_TYPE_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    content_type: _builtins.str
    """content_typeはimage/jpegか、image/pngのいずれかを指定します。"""
    data: _builtins.bytes
    """画像データです。10MBまでの画像を指定できます。"""
    def __init__(
        self,
        *,
        content_type: _builtins.str = ...,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content_type", b"content_type", "data", b"data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventPicture: _TypeAlias = EventPicture  # noqa: Y015

@_typing.final
class ObjectPicture(_message.Message):
    """ObjectPictureは、オブジェクトに付与される画像情報を表します"""

    DESCRIPTOR: _descriptor.Descriptor

    LABEL_FIELD_NUMBER: _builtins.int
    CONTENT_TYPE_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    label: _builtins.str
    """オブジェクトに付与された画像の識別子。正規表現 ^[a-zA-Z0-9_\\\\-]+$ にマッチした16文字以内の文字列を指定できます。"""
    content_type: _builtins.str
    """content_typeはimage/jpegか、image/pngのいずれかを指定します。"""
    data: _builtins.bytes
    """画像データです。10MBまでの画像を指定できます。"""
    def __init__(
        self,
        *,
        label: _builtins.str = ...,
        content_type: _builtins.str = ...,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content_type", b"content_type", "data", b"data", "label", b"label"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ObjectPicture: _TypeAlias = ObjectPicture  # noqa: Y015

@_typing.final
class ObjectExtraData(_message.Message):
    """ObjectExtraDataは、オブジェクトに付与される追加のデータを表します"""

    DESCRIPTOR: _descriptor.Descriptor

    CONTENT_TYPE_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    content_type: _builtins.str
    """content_typeは、MIMEタイプ表記で指定します。（例: image/jpeg）"""
    data: _builtins.bytes
    """追加のデータです。10MBまでのデータを指定できます。"""
    def __init__(
        self,
        *,
        content_type: _builtins.str = ...,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content_type", b"content_type", "data", b"data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ObjectExtraData: _TypeAlias = ObjectExtraData  # noqa: Y015

@_typing.final
class DeviceStatus(_message.Message):
    """DeviceStatusは、デバイスのステータス情報を表します"""

    DESCRIPTOR: _descriptor.Descriptor

    LABEL_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    SCORE_FIELD_NUMBER: _builtins.int
    GEOMETRY_CONFIG_IDS_FIELD_NUMBER: _builtins.int
    label: _builtins.str
    """ステータスの識別子です。
    同じラベルを持つステータスは同一のステータスとして扱われ、上書きされます
    """
    status: _builtins.str
    """ステータスを表す文字列です。"""
    score: _builtins.float
    """ステータスを表す数値データです。
    有効数字6桁までで、6桁より先は四捨五入されます。
    """
    @_builtins.property
    def geometry_config_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """ステータスが関連するジオメトリ設定IDのリストです。"""

    def __init__(
        self,
        *,
        label: _builtins.str = ...,
        status: _builtins.str = ...,
        score: _builtins.float | None = ...,
        geometry_config_ids: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_score", b"_score", "score", b"score"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_score", b"_score", "geometry_config_ids", b"geometry_config_ids", "label", b"label", "score", b"score", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__score: _TypeAlias = _typing.Literal["score"]  # noqa: Y015
    _WhichOneofArgType__score: _TypeAlias = _typing.Literal["_score", b"_score"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__score) -> _WhichOneofReturnType__score | None: ...

Global___DeviceStatus: _TypeAlias = DeviceStatus  # noqa: Y015
